//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrativAvProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemperatureCollection
    {
        public long Id { get; set; }
        public string TemDate { get; set; }
        public string Time { get; set; }
        public string Temperature { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string DistrictName { get; set; }
    }
}
